2025-05-08 11:38:19,492 INFO: Super admin user already exists [in C:\Users\bhave\OneDrive\Desktop\G31_HealthCareAppointmentBookingSystem_api\G31_HealthCareAppointmentBookingSystem_Flask\app.py:910]
2025-05-08 12:22:00,146 INFO: Healthcare Appointment System startup [in C:\Users\bhave\OneDrive\Desktop\G31_HealthCareAppointmentBookingSystem_api\G31_HealthCareAppointmentBookingSystem_Flask\app.py:547]
2025-05-08 12:22:00,456 INFO: Super admin user created successfully [in C:\Users\bhave\OneDrive\Desktop\G31_HealthCareAppointmentBookingSystem_api\G31_HealthCareAppointmentBookingSystem_Flask\app.py:592]
2025-05-08 12:22:00,456 INFO: Super admin user created [in C:\Users\bhave\OneDrive\Desktop\G31_HealthCareAppointmentBookingSystem_api\G31_HealthCareAppointmentBookingSystem_Flask\app.py:908]
2025-05-08 12:22:20,342 INFO: Healthcare Appointment System startup [in C:\Users\bhave\OneDrive\Desktop\G31_HealthCareAppointmentBookingSystem_api\G31_HealthCareAppointmentBookingSystem_Flask\app.py:547]
2025-05-08 12:22:20,360 INFO: Super admin user already exists [in C:\Users\bhave\OneDrive\Desktop\G31_HealthCareAppointmentBookingSystem_api\G31_HealthCareAppointmentBookingSystem_Flask\app.py:910]
2025-05-08 12:25:28,157 INFO: Healthcare Appointment System startup [in C:\Users\bhave\OneDrive\Desktop\G31_HealthCareAppointmentBookingSystem_api\G31_HealthCareAppointmentBookingSystem_Flask\app.py:547]
2025-05-08 12:25:28,173 INFO: Super admin user already exists [in C:\Users\bhave\OneDrive\Desktop\G31_HealthCareAppointmentBookingSystem_api\G31_HealthCareAppointmentBookingSystem_Flask\app.py:910]
2025-05-08 12:39:20,809 INFO: Healthcare Appointment System startup [in C:\Users\bhave\OneDrive\Desktop\G31_HealthCareAppointmentBookingSystem_api\G31_HealthCareAppointmentBookingSystem_Flask\app.py:547]
2025-05-08 12:39:20,831 INFO: Super admin user already exists [in C:\Users\bhave\OneDrive\Desktop\G31_HealthCareAppointmentBookingSystem_api\G31_HealthCareAppointmentBookingSystem_Flask\app.py:910]
2025-05-08 12:39:25,493 ERROR: Exception on / [GET] [in C:\Users\bhave\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\bhave\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bhave\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bhave\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\bhave\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_restful\__init__.py", line 298, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bhave\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bhave\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bhave\OneDrive\Desktop\G31_HealthCareAppointmentBookingSystem_api\G31_HealthCareAppointmentBookingSystem_Flask\app.py", line 602, in landing
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bhave\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bhave\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bhave\AppData\Local\Programs\Python\Python312\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\bhave\AppData\Local\Programs\Python\Python312\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\bhave\OneDrive\Desktop\G31_HealthCareAppointmentBookingSystem_api\G31_HealthCareAppointmentBookingSystem_Flask\templates\index.html", line 18, in top-level template code
    {% extends 'base.html' %}
  File "C:\Users\bhave\OneDrive\Desktop\G31_HealthCareAppointmentBookingSystem_api\G31_HealthCareAppointmentBookingSystem_Flask\templates\base.html", line 35, in top-level template code
    <li><a href="{{url_for('my_appointments')}}">My Appointments</a></li>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bhave\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1071, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bhave\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1060, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bhave\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\routing\map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'my_appointments'. Did you mean 'appointments' instead?
